sudo: required
dist: trusty
language: java
jdk:
- openjdk11
branches:
  only:
  - develop
  - master
notifications:
  slack:
    on_success: change
    on_failure: always
    secure: PcW6FAMLtgCovHBkQESfWiJ8sLkBeseebOr8yjtYyDtHIvf0/j8o473EIEjK+CwjQM4Ss5dMThnO6+glm6L319EOtVJNxotPG88VA6HQ7niy4wLZYfAYHUnfdQErCxfiy63szO+UrdiINPThnIajwWGMXvMx7j8FX0XUkRINmMIwWLEuKPxUfdUMZ8px52sfUG+VYrorGc02DbtOErsL2XmRkp3ihKqDooDN0grYfOjoVsZQc6F2pmdwNAEULeKvhQMvf4Nl4ilw4cyGojWWvNKGG8q7AnsL/HamDo/rtCVK3roZzCSrzV5xUbB6lbtt3z9S3wQJxuqh/X6Ht7R7m9RU0fd2e3MhXOrM+r3vEeh/S1OuZhsB5cIADKyCLU7WnI/XOBiqCktFVcWTGerqULcnKil75NncE1aYAZ+Rr03iH2DPwxkLReYbZqZlJUL59bUWsm8vqy+Wk43zgMd4Pcq9r/BQKqCYqh5vmrcZtURIPvG9b57bsjlIhXDAnURxliYvvhMbAeIanJHUv8vRatjQ78np25+afZNvXbCnGjm+7kQGMQCWQL8Xx10TJHQBibiox9U7XYYO8uzpK9bfcYTGxIQMrk9Pu7YijdkAV+55k6/AQNhjP8UGuUo2LZWHC+rSxQ5hLms2NqZ7P+Ggw0/8Fj+ldkWCWMxaOkaTiGk=
install: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn -DskipTests=false clean deploy
  --settings .m2/travis-settings.xml'
script: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn -DskipTests=true clean --settings
  .m2/travis-settings.xml'
env:
  global:
  - CEDAR_HOME=/home/cedar/
  - CEDAR_HOST=metadatacenter.orgx
  - CEDAR_ADMIN_USER_PASSWORD=adminPassword
  - CEDAR_ADMIN_USER_API_KEY=1234
  - CEDAR_MONGO_APP_USER_NAME=cedarUser
  - CEDAR_MONGO_APP_USER_PASSWORD=password
  - CEDAR_SALT_API_KEY=saltme
  - secure: ZbWptjIG0jX+Jv2kzW6vA+qZEIWj8t11PcJ+sX0WhutzZ0nS4NbzuwkjjhoYtsDOPznjlaxwa/knbMkCYpkCRb+0L7BMFgBCitnFp9onPFhWbACovC2Xpv0sYTrF/oAHuuy41IGwHYxs+wHsKblQmLF4Oz98eE9KgxiYfZjy2IwfHXuTHk4+gTX2s+pxvT2A7tOliGEwF3mUSo66+VuEXnQEAp3LvO/aI9sKawCaVk0CaTEBcYelnMlVA2sQLvWnhxByDlgD7GbJRiT4AG0lNvk+8Bl+AyBdtGbmvaFTgVnGqv5EaA1FOXGdtbJ0As8gd69g/tLFtRH0qNvv625FcqQGZjCZbhJK+pPDDTFUnna5rsKxBMy7Y+hiSIpEPE6R7QLq+xsDKshMqUX7sRkJHt8MRM87LEcu5P1RmYYYPwABYIrE+8v/VKNZ7dg9CGMKeMgI7jZiunZ4eEJUhXVpBZ8c8rd26OnWcj2uxaY7HIQ8I3ccQHmigoaSzu454DAV10nZ2hj2Nei+RnM/1d0OFHsNC4uYpKS6ZlB1Ecs4dS2ijMQW7N7HpsTdBUKivBnwvtpzPfp78DzVbST+Ld9Sfm6orWR1D0WxS4U7WBbaK9yWpURVAqCIjix+i8oP9GmEr52ZeZ1Xh6zIHuSNyjerA5pDebaHOI9nIJ086Fli3xI=
  - secure: O2Z/nskEL9ibAfngxLBGhGaY+DDky0i5BqHlngjReX5T59UnkNN11ENP5esIPEBJl7wrJ2IqV69tdo16uTEJM2qBQOJD6gpbXm4pXJomV4c5r4Q0y7eMb+HOLgExMmRc4FVhDw1VKR9wk3hnZOepWMCHTDAGRT9jnHjue+Fyb/rhedEIKc4wSq6kNn+nRW4DiygQtlSGu23hQmNr+rvOtxXCL4yPkSuKSu7nMjI2uEOzM27KfpdSgkcgAwylcmEZA3IHrE/XzOvi0asm2dG1bJ+a9WWkSgvLFyqgo5tRau/WVm6BR7Cgh7XjJGXKRJjfkde4fS+j1mk+nIpQdgY3g6VokQJ/DVPDpkdlFKv6o4s4lKKdBgPYVsmti242D/Yd4pqx0TdTPJeBBwfgZ0tKYeYWHmF41pSsizpHLZJo2yvpe3F0rhuxoU3SaW9lUVVnTqqO7bdemerFsVpU+vbcDVTICz8FsT6ZdCNUzQNhMBx5WT/n0usePCpxaonO0YofNNQsexBUSGXmJsBMbjkks7NTcnAVBqvvDICXOuyMzM8jKzKUwrQrst8HhXbsT7aldTAGAoRVZPAPejkrY3Gqth2P9Q4gQKaR2gLbbzupdr3Ynr84nWcFq9wxozrFceRcKRSNTyiu+6XwFJHoZLbTPHQk8l54Sq4EV2F7QsroBLY=
