sudo: required
dist: trusty

language: java
jdk:
- oraclejdk8
branches:
  only:
  - develop
  - master
cache:
  directories:
  - $HOME/.m2
notifications:
  email:
    recipients:
    - cedar-core-developers@lists.stanford.edu
    on_success: never
    on_failure: always
install: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn -DskipTests=true clean deploy --settings .m2/travis-settings.xml'
env:
  global:
  - secure: ZbWptjIG0jX+Jv2kzW6vA+qZEIWj8t11PcJ+sX0WhutzZ0nS4NbzuwkjjhoYtsDOPznjlaxwa/knbMkCYpkCRb+0L7BMFgBCitnFp9onPFhWbACovC2Xpv0sYTrF/oAHuuy41IGwHYxs+wHsKblQmLF4Oz98eE9KgxiYfZjy2IwfHXuTHk4+gTX2s+pxvT2A7tOliGEwF3mUSo66+VuEXnQEAp3LvO/aI9sKawCaVk0CaTEBcYelnMlVA2sQLvWnhxByDlgD7GbJRiT4AG0lNvk+8Bl+AyBdtGbmvaFTgVnGqv5EaA1FOXGdtbJ0As8gd69g/tLFtRH0qNvv625FcqQGZjCZbhJK+pPDDTFUnna5rsKxBMy7Y+hiSIpEPE6R7QLq+xsDKshMqUX7sRkJHt8MRM87LEcu5P1RmYYYPwABYIrE+8v/VKNZ7dg9CGMKeMgI7jZiunZ4eEJUhXVpBZ8c8rd26OnWcj2uxaY7HIQ8I3ccQHmigoaSzu454DAV10nZ2hj2Nei+RnM/1d0OFHsNC4uYpKS6ZlB1Ecs4dS2ijMQW7N7HpsTdBUKivBnwvtpzPfp78DzVbST+Ld9Sfm6orWR1D0WxS4U7WBbaK9yWpURVAqCIjix+i8oP9GmEr52ZeZ1Xh6zIHuSNyjerA5pDebaHOI9nIJ086Fli3xI=
  - secure: O2Z/nskEL9ibAfngxLBGhGaY+DDky0i5BqHlngjReX5T59UnkNN11ENP5esIPEBJl7wrJ2IqV69tdo16uTEJM2qBQOJD6gpbXm4pXJomV4c5r4Q0y7eMb+HOLgExMmRc4FVhDw1VKR9wk3hnZOepWMCHTDAGRT9jnHjue+Fyb/rhedEIKc4wSq6kNn+nRW4DiygQtlSGu23hQmNr+rvOtxXCL4yPkSuKSu7nMjI2uEOzM27KfpdSgkcgAwylcmEZA3IHrE/XzOvi0asm2dG1bJ+a9WWkSgvLFyqgo5tRau/WVm6BR7Cgh7XjJGXKRJjfkde4fS+j1mk+nIpQdgY3g6VokQJ/DVPDpkdlFKv6o4s4lKKdBgPYVsmti242D/Yd4pqx0TdTPJeBBwfgZ0tKYeYWHmF41pSsizpHLZJo2yvpe3F0rhuxoU3SaW9lUVVnTqqO7bdemerFsVpU+vbcDVTICz8FsT6ZdCNUzQNhMBx5WT/n0usePCpxaonO0YofNNQsexBUSGXmJsBMbjkks7NTcnAVBqvvDICXOuyMzM8jKzKUwrQrst8HhXbsT7aldTAGAoRVZPAPejkrY3Gqth2P9Q4gQKaR2gLbbzupdr3Ynr84nWcFq9wxozrFceRcKRSNTyiu+6XwFJHoZLbTPHQk8l54Sq4EV2F7QsroBLY=
